### ISSUE TITLE
Unable to run in node

### ISSUE THREAD

**Issue by kokarn** [pirxpilot/tweet-html#2]
Because the main file specifies `ago` and `el` instead of `yield-ago` and `el-component` it fails to run under node.

I believe the browser field is no longer needed if those require's are just updated.

Is that something you'd be open to incorporate?
I'd be open to submitting a PR if that's the case.

**Comment by pirxpilot** [comment]
Yup. PR welcome.
I'll probably try to rewrite tests to just run under node and `jsdom` instead of `mochify`
